const mongoose = require("mongoose");
const { Schema } = mongoose;

const cardinalItemSchema = new Schema({
  cin: { type: String, unique: true },
  //   tradeName: String,
  //   labelName: String,
  //   genericName: String,
  //   ndc: String,
  // strength: String,
  //   form: String,
  //   packageQty: String,
  // packageSize: String,
  //   unit: String,
  //   cardinalContract: String,
  //   cardinalStockStatus: String,
  //   cardinalQtyAvailable: String,
  //   cardinalCost: String,
  //   cardinalRetailPriceChanged: String,
  //   mfr: String,
  //   dist: String,
  //   productType: String,
  //   deaSchedule: String,
  //   abRating: String,
  //   returnPackaging: String,
  //   specialty: String,
  //   altCIN: [String],
  //   altNDC: [String],
  //   altTradeName: [String],
  //   altStrength: [String],
  //   altForm: [String],
  //   altSize: [String],
  //   altType: [String],
  //   altCost: [String],
  //   altContract: [String],
  //   cardinalHistOrderDate: [String],
  //   cardinalHistInvoiceDate: [String],
  //   cardinalHistOrderQty: [String],
  //   cardinalHistShipQty: [String],
  //   cardinalHistUnitCost: [String],
  //   cardinalHistTotalCost: [String],
  //   cardinalHistInvoiceNum: [String],
  //   cardinalHistOrderMethod: [String],
  //   cardinalWACEffectiveDate: [String],
  //   cardinalWAC: [String],
  //   cardinalWACPercentChange: [String],
  //   dateLastUpdatedCardinal: Date,
  //   lastDateCardinalPriceMatched: Date,
});

module.exports = mongoose.model("Cardinal Item", cardinalItemSchema);
